"""Generate the TypeScript protocol types (`vscode/src/protocol.ts`) from the
pydantic models, so the extension and the agent can't disagree.

Run `cmcoder protocol-schema --typescript > vscode/src/protocol.ts`; a test
fails when the file is out of date.

The schema is simple (strings, numbers, booleans, lists, open objects,
literals, optional values), so a small generator is enough.
"""

from __future__ import annotations

import json
from typing import Any

from .events import PROTOCOL_VERSION, protocol_json_schema
from .messages import messages_json_schema

HEADER = """\
// Generated by `cmcoder protocol-schema --typescript` from
// src/cmcoder/protocol/{events,messages}.py. Do not edit by hand.
/* eslint-disable */
"""


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:  # a nested model, e.g. "#/$defs/FileChange"
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(s) for s in schema["anyOf"])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        item = ts_type(schema.get("items", {}))
        return f"({item})[]" if "|" in item else f"{item}[]"
    if kind == "object":
        return "Record<string, unknown>"
    return "unknown"


def _comment(text: str) -> list[str]:
    lines = text.strip().splitlines()
    if len(lines) == 1:
        return [f"/** {lines[0]} */"]
    return ["/**", *(f" * {x}".rstrip() for x in lines), " */"]


def _interface(name: str, schema: dict[str, Any], defaults_optional: bool) -> list[str]:
    out = _comment(schema["description"]) if schema.get("description") else []
    out.append(f"export interface {name} {{")
    required = set(schema.get("required", []))
    for field, prop in schema["properties"].items():
        # The agent always sends every field; the client may leave out defaults.
        optional = defaults_optional and field not in required and field != "type"
        out.append(f"  {field}{'?' if optional else ''}: {ts_type(prop)};")
    out.append("}")
    return out


def _union(
    title: str, schema: dict[str, Any], defaults_optional: bool
) -> tuple[list[str], list[str]]:
    names = [ref["$ref"].split("/")[-1] for ref in schema["oneOf"]]
    lines: list[str] = []
    # Nested models (not members of the union) first, e.g. FileChange.
    for name in sorted(set(schema["$defs"]) - set(names)):
        lines += _interface(name, schema["$defs"][name], defaults_optional)
        lines.append("")
    for name in names:
        lines += _interface(name, schema["$defs"][name], defaults_optional)
        lines.append("")
    lines.append(f"export type {title} =")
    lines += [f"  | {n}" for n in names[:-1]]
    lines.append(f"  | {names[-1]};")
    return lines, names


def generate_typescript() -> str:
    events, event_names = _union("AgentEvent", protocol_json_schema(), defaults_optional=False)
    messages, message_names = _union(
        "ClientMessage", messages_json_schema(), defaults_optional=True
    )
    clash = set(event_names) & set(message_names)
    assert not clash, f"an event and a message share a name: {clash}"
    parts = [
        HEADER,
        f"export const PROTOCOL_VERSION = {PROTOCOL_VERSION};",
        "",
        "// ---- Agent -> client (stdout) ----",
        "",
        *events,
        "",
        "// ---- Client -> agent (stdin) ----",
        "",
        *messages,
        "",
    ]
    return "\n".join(parts)
