// Generated by `cmcoder protocol-schema --typescript` from
// src/cmcoder/protocol/{events,messages}.py. Do not edit by hand.
/* eslint-disable */

export const PROTOCOL_VERSION = 1;

// ---- Agent -> client (stdout) ----

export interface SystemInit {
  type: "system_init";
  protocol_version: number;
  session_id: string;
  cwd: string;
  model: string;
  provider: string;
  tools: string[];
  permission_mode: string;
}

export interface AssistantDelta {
  type: "assistant_delta";
  text: string;
}

export interface ReasoningDelta {
  type: "reasoning_delta";
  text: string;
}

export interface AssistantMessage {
  type: "assistant_message";
  text: string;
  reasoning: string;
  tool_calls: Record<string, unknown>[];
  model: string | null;
}

export interface ToolUse {
  type: "tool_use";
  id: string;
  name: string;
  input: Record<string, unknown>;
  label: string;
}

export interface ToolResult {
  type: "tool_result";
  id: string;
  name: string;
  content: string;
  is_error: boolean;
  summary: string | null;
}

export interface PermissionDenied {
  type: "permission_denied";
  id: string;
  name: string;
  reason: string;
}

export interface UsageUpdate {
  type: "usage";
  prompt_tokens: number;
  completion_tokens: number;
  estimated: boolean;
  cost: number | null;
  context_window: number | null;
}

export interface Warning {
  type: "warning";
  message: string;
}

export interface Error {
  type: "error";
  kind: string;
  message: string;
  hint: string | null;
}

/** The older part of the conversation was replaced by a summary. */
export interface Compacted {
  type: "compacted";
  trigger: "auto" | "manual";
  summarized_messages: number;
  tokens_before: number;
  tokens_after: number;
  model: string;
}

/**
 * The agent needs the user's approval for a tool call (stdio protocol).
 *
 * Answer with a `permission_response` carrying the same `request_id`.
 */
export interface PermissionRequest {
  type: "permission_request";
  request_id: string;
  tool_use_id: string;
  name: string;
  label: string;
  input: Record<string, unknown>;
  suggested_rule: string;
  reason: string;
  can_remember: boolean;
}

/** The todo list changed (stdio protocol). */
export interface TodoUpdate {
  type: "todo_update";
  todos: Record<string, unknown>[];
}

export interface ModeChanged {
  type: "mode_changed";
  mode: string;
}

export interface ModelChanged {
  type: "model_changed";
  model: string;
  context_window: number | null;
}

export interface Result {
  type: "result";
  subtype: "success" | "error" | "max_turns" | "interrupted";
  is_error: boolean;
  result: string;
  num_turns: number;
  duration_ms: number;
  usage: Record<string, unknown>;
  session_id: string;
}

export type AgentEvent =
  | SystemInit
  | AssistantDelta
  | ReasoningDelta
  | AssistantMessage
  | ToolUse
  | ToolResult
  | PermissionDenied
  | UsageUpdate
  | Warning
  | Error
  | Compacted
  | PermissionRequest
  | TodoUpdate
  | ModeChanged
  | ModelChanged
  | Result;

// ---- Client -> agent (stdin) ----

/** Start a turn. Only one turn runs at a time. */
export interface UserMessage {
  type: "user_message";
  text: string;
}

/** Stop the running turn (like Ctrl+C in the CLI). */
export interface Interrupt {
  type: "interrupt";
}

/** The answer to a `permission_request`. */
export interface PermissionResponse {
  type: "permission_response";
  request_id: string;
  allow: boolean;
  remember?: boolean;
  feedback?: string | null;
}

export interface SetMode {
  type: "set_mode";
  mode: string;
}

export interface SetModel {
  type: "set_model";
  model: string;
}

/** Stop the running turn, save the session and exit (EOF does the same). */
export interface Shutdown {
  type: "shutdown";
}

export type ClientMessage =
  | UserMessage
  | Interrupt
  | PermissionResponse
  | SetMode
  | SetModel
  | Shutdown;
