// Generated by `cmcoder protocol-schema --typescript` from
// src/cmcoder/protocol/{events,messages}.py. Do not edit by hand.
/* eslint-disable */

export const PROTOCOL_VERSION = 1;

// ---- Agent -> client (stdout) ----

export interface CommandInfo {
  name: string;
  description: string;
  argument_hint: string;
  origin: "built-in" | "user" | "project" | "mcp";
}

/** A proposed file change, for review in a diff editor. */
export interface FileChange {
  path: string;
  before: string | null;
  after: string;
}

export interface HistoryItem {
  role: "user" | "assistant" | "tool";
  text: string;
}

export interface RewindAction {
  path: string;
  action: string;
}

export interface RewindPoint {
  turn: number;
  text: string;
  files_changed: number;
  outside_files: string[];
}

export interface SessionSummary {
  id: string;
  title: string;
  updated: number;
  messages: number;
}

export interface SystemInit {
  type: "system_init";
  protocol_version: number;
  session_id: string;
  cwd: string;
  model: string;
  provider: string;
  tools: string[];
  permission_mode: string;
}

export interface AssistantDelta {
  type: "assistant_delta";
  text: string;
}

export interface ReasoningDelta {
  type: "reasoning_delta";
  text: string;
}

export interface AssistantMessage {
  type: "assistant_message";
  text: string;
  reasoning: string;
  tool_calls: Record<string, unknown>[];
  model: string | null;
}

export interface ToolUse {
  type: "tool_use";
  id: string;
  name: string;
  input: Record<string, unknown>;
  label: string;
  parent_tool_use_id: string | null;
}

export interface ToolResult {
  type: "tool_result";
  id: string;
  name: string;
  content: string;
  is_error: boolean;
  summary: string | null;
  parent_tool_use_id: string | null;
}

export interface PermissionDenied {
  type: "permission_denied";
  id: string;
  name: string;
  reason: string;
  parent_tool_use_id: string | null;
}

export interface UsageUpdate {
  type: "usage";
  prompt_tokens: number;
  completion_tokens: number;
  estimated: boolean;
  cost: number | null;
  context_window: number | null;
}

export interface Warning {
  type: "warning";
  message: string;
}

export interface Error {
  type: "error";
  kind: string;
  message: string;
  hint: string | null;
}

/** The older part of the conversation was replaced by a summary. */
export interface Compacted {
  type: "compacted";
  trigger: "auto" | "manual";
  summarized_messages: number;
  tokens_before: number;
  tokens_after: number;
  model: string;
}

/**
 * The agent needs the user's approval for a tool call (stdio protocol).
 *
 * Answer with a `permission_response` carrying the same `request_id`.
 */
export interface PermissionRequest {
  type: "permission_request";
  request_id: string;
  tool_use_id: string;
  name: string;
  label: string;
  input: Record<string, unknown>;
  suggested_rule: string;
  reason: string;
  can_remember: boolean;
  change: FileChange | null;
}

/** The todo list changed (stdio protocol). */
export interface TodoUpdate {
  type: "todo_update";
  todos: Record<string, unknown>[];
}

export interface ModeChanged {
  type: "mode_changed";
  mode: string;
}

export interface ModelChanged {
  type: "model_changed";
  model: string;
  context_window: number | null;
}

/** Run an IDE tool in the client; answer with `ide_tool_result`. */
export interface IdeToolRequest {
  type: "ide_tool_request";
  request_id: string;
  name: string;
  input: Record<string, unknown>;
}

export interface SessionList {
  type: "session_list";
  sessions: SessionSummary[];
}

/** The slash commands a `user_message` can start with (for completion). */
export interface CommandList {
  type: "command_list";
  commands: CommandInfo[];
}

/** Earlier user messages to rewind to (answer with a `rewind` message). */
export interface RewindPoints {
  type: "rewind_points";
  points: RewindPoint[];
}

/**
 * The result of a `rewind`. When the conversation was rewound, a
 * `history` event follows with the conversation as it is now.
 */
export interface Rewound {
  type: "rewound";
  code: boolean;
  conversation: boolean;
  actions: RewindAction[];
  prompt: string | null;
}

/** A resumed conversation so far, so the client can show it. */
export interface History {
  type: "history";
  messages: HistoryItem[];
}

export interface Result {
  type: "result";
  subtype: "success" | "error" | "max_turns" | "interrupted";
  is_error: boolean;
  result: string;
  num_turns: number;
  duration_ms: number;
  usage: Record<string, unknown>;
  session_id: string;
}

export type AgentEvent =
  | SystemInit
  | AssistantDelta
  | ReasoningDelta
  | AssistantMessage
  | ToolUse
  | ToolResult
  | PermissionDenied
  | UsageUpdate
  | Warning
  | Error
  | Compacted
  | PermissionRequest
  | TodoUpdate
  | ModeChanged
  | ModelChanged
  | IdeToolRequest
  | SessionList
  | CommandList
  | RewindPoints
  | Rewound
  | History
  | Result;

// ---- Client -> agent (stdin) ----

/** What the user has open in the editor, sent with a message. */
export interface IdeContext {
  active_file?: string | null;
  selection?: IdeSelection | null;
  diagnostics?: IdeDiagnostic[];
}

export interface IdeDiagnostic {
  path: string;
  line: number;
  severity: "error" | "warning" | "info" | "hint";
  message: string;
  source?: string | null;
}

export interface IdeSelection {
  path: string;
  start_line: number;
  end_line: number;
  text: string;
}

/** Start a turn. Only one turn runs at a time. */
export interface UserMessage {
  type: "user_message";
  text: string;
  context?: IdeContext | null;
}

/** Stop the running turn (like Ctrl+C in the CLI). */
export interface Interrupt {
  type: "interrupt";
}

/** The answer to a `permission_request`. */
export interface PermissionResponse {
  type: "permission_response";
  request_id: string;
  allow: boolean;
  remember?: boolean;
  feedback?: string | null;
}

export interface SetMode {
  type: "set_mode";
  mode: string;
}

export interface SetModel {
  type: "set_model";
  model: string;
}

/**
 * The client can run these IDE tools (e.g. getDiagnostics, openFile).
 *
 * Send once after `system_init`; the agent offers them to the model and
 * asks the client to run them with `ide_tool_request`.
 */
export interface IdeCapabilities {
  type: "ide_capabilities";
  tools: string[];
}

/** The answer to an `ide_tool_request`. */
export interface IdeToolResult {
  type: "ide_tool_result";
  request_id: string;
  content: string;
  is_error?: boolean;
}

/** Ask for this project's saved conversations (answered with `session_list`). */
export interface ListSessions {
  type: "list_sessions";
}

/**
 * Ask for the slash commands (answered with `command_list`). A
 * `user_message` whose text starts with one of them runs it.
 */
export interface ListCommands {
  type: "list_commands";
}

/**
 * Go back to before user message `turn` (from `rewind_points`): undo the
 * agent's file changes (`code`), the conversation, or both. Files outside the
 * project are only restored with `outside`.
 */
export interface Rewind {
  type: "rewind";
  turn: number;
  code?: boolean;
  conversation?: boolean;
  outside?: boolean;
}

/** Stop the running turn, save the session and exit (EOF does the same). */
export interface Shutdown {
  type: "shutdown";
}

export type ClientMessage =
  | UserMessage
  | Interrupt
  | PermissionResponse
  | SetMode
  | SetModel
  | IdeCapabilities
  | IdeToolResult
  | ListSessions
  | ListCommands
  | Rewind
  | Shutdown;
