"""The product's name, accent colour and text logo, from the `branding/`
folder (see branding/README.md). Packaged with cmcoder: in the wheel and the
standalone build as `cmcoder/_brand/`; from a source checkout, the repository's
`branding/` itself. Anything missing or invalid falls back to the defaults, so
a bad branding file never stops cmcoder (packaging/brand.py rejects it at
build time instead)."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import cache
from pathlib import Path

DEFAULT_NAME = "cmcoder"
DEFAULT_ACCENT = "#4F8EF7"
LOGO_MAX_LINES = 8
LOGO_MAX_WIDTH = 60
NAME_MAX = 40
COLOR = re.compile(r"^#[0-9A-Fa-f]{6}$")
# VS Code's publisher ID rules (vsce): letters, digits and hyphens.
PUBLISHER = re.compile(r"^[A-Za-z0-9][A-Za-z0-9-]{0,62}$")


@dataclass(frozen=True)
class Brand:
    product_name: str = DEFAULT_NAME
    accent_color: str = DEFAULT_ACCENT
    logo: str | None = None
    folder: Path | None = None

    @property
    def icon_png(self) -> Path | None:
        p = self.folder / "icon.png" if self.folder else None
        return p if p is not None and p.is_file() else None

    @property
    def icon_ico(self) -> Path | None:
        """cmcoder.ico (generated by packaging/brand.py; standalone build only)."""
        p = self.folder / "cmcoder.ico" if self.folder else None
        return p if p is not None and p.is_file() else None


def folders() -> list[Path]:
    here = Path(__file__).resolve().parent
    return [here / "_brand", here.parent.parent / "branding"]


def problems(data: object, logo: str | None) -> list[str]:
    """What's wrong with a brand.json's contents and a logo.txt (empty: fine)."""
    out: list[str] = []
    if not isinstance(data, dict):
        return ["brand.json must contain a JSON object"]
    known = {"productName", "publisher", "company", "copyright", "accentColor"}
    out += [f"brand.json: unknown key {k!r}" for k in data if k not in known]
    name = data.get("productName", DEFAULT_NAME)
    if (
        not isinstance(name, str)
        or not name.strip()
        or len(name) > NAME_MAX
        or not name.isprintable()
    ):
        out.append(f"brand.json: productName must be 1-{NAME_MAX} printable characters")
    publisher = data.get("publisher", DEFAULT_NAME)
    if not isinstance(publisher, str) or not PUBLISHER.match(publisher):
        out.append("brand.json: publisher may only have letters, digits and hyphens")
    for key in ("company", "copyright"):
        value = data.get(key, "")
        if not isinstance(value, str) or len(value) > 100 or not value.isprintable():
            out.append(f"brand.json: {key} must be text of at most 100 printable characters")
    color = data.get("accentColor", DEFAULT_ACCENT)
    if not isinstance(color, str) or not COLOR.match(color):
        out.append("brand.json: accentColor must look like #4F8EF7")
    if logo is not None:
        lines = logo.splitlines()
        if len(lines) > LOGO_MAX_LINES or any(len(x) > LOGO_MAX_WIDTH for x in lines):
            out.append(f"logo.txt: at most {LOGO_MAX_LINES} lines of {LOGO_MAX_WIDTH} characters")
        if any(not x.isprintable() for x in lines):
            out.append("logo.txt: control characters (e.g. escape codes) aren't allowed")
    return out


def read_folder(folder: Path) -> tuple[dict[str, object], str | None]:
    data = json.loads((folder / "brand.json").read_text(encoding="utf-8-sig"))
    logo_file = folder / "logo.txt"
    logo = logo_file.read_text(encoding="utf-8-sig").rstrip() if logo_file.is_file() else None
    return data, logo or None


@cache
def load() -> Brand:
    for folder in folders():
        if not (folder / "brand.json").is_file():
            continue
        try:
            data, logo = read_folder(folder)
        except (OSError, ValueError):
            return Brand()
        if problems(data, logo):
            return Brand(folder=folder)
        assert isinstance(data, dict)
        return Brand(
            product_name=str(data.get("productName", DEFAULT_NAME)).strip(),
            accent_color=str(data.get("accentColor", DEFAULT_ACCENT)),
            logo=logo,
            folder=folder,
        )
    return Brand()
