// Generated by `cmcoder protocol-schema --typescript` from
// src/cmcoder/protocol/{events,messages}.py. Do not edit by hand.
/* eslint-disable */

export const PROTOCOL_VERSION = 1;

// ---- Agent -> client (stdout) ----

export interface CodeContextItem {
  path: string;
  start_line: number;
  end_line: number;
  symbol: string | null;
  score: number;
}

export interface CommandInfo {
  name: string;
  description: string;
  argument_hint: string;
  origin: "built-in" | "user" | "project" | "mcp";
}

/** A proposed file change, for review in a diff editor. */
export interface FileChange {
  path: string;
  before: string | null;
  after: string;
}

export interface HistoryItem {
  role: "user" | "assistant" | "tool";
  text: string;
}

export interface ReviewIssue {
  severity: "high" | "medium" | "low";
  problem: string;
  where: string;
  fix: string;
}

export interface RewindAction {
  path: string;
  action: string;
}

export interface RewindPoint {
  turn: number;
  text: string;
  files_changed: number;
  outside_files: string[];
}

export interface SessionSummary {
  id: string;
  title: string;
  updated: number;
  messages: number;
}

export interface SystemInit {
  type: "system_init";
  protocol_version: number;
  session_id: string;
  cwd: string;
  model: string;
  provider: string;
  tools: string[];
  permission_mode: string;
  critique: boolean;
}

export interface AssistantDelta {
  type: "assistant_delta";
  text: string;
}

export interface ReasoningDelta {
  type: "reasoning_delta";
  text: string;
}

export interface AssistantMessage {
  type: "assistant_message";
  text: string;
  reasoning: string;
  tool_calls: Record<string, unknown>[];
  model: string | null;
}

export interface ToolUse {
  type: "tool_use";
  id: string;
  name: string;
  input: Record<string, unknown>;
  label: string;
  parent_tool_use_id: string | null;
}

export interface ToolResult {
  type: "tool_result";
  id: string;
  name: string;
  content: string;
  is_error: boolean;
  summary: string | null;
  parent_tool_use_id: string | null;
}

export interface PermissionDenied {
  type: "permission_denied";
  id: string;
  name: string;
  reason: string;
  parent_tool_use_id: string | null;
}

export interface UsageUpdate {
  type: "usage";
  prompt_tokens: number;
  completion_tokens: number;
  estimated: boolean;
  cost: number | null;
  context_window: number | null;
}

export interface Warning {
  type: "warning";
  message: string;
}

export interface Error {
  type: "error";
  kind: string;
  message: string;
  hint: string | null;
}

/** The older part of the conversation was replaced by a summary. */
export interface Compacted {
  type: "compacted";
  trigger: "auto" | "manual";
  summarized_messages: number;
  tokens_before: number;
  tokens_after: number;
  model: string;
}

/**
 * The agent needs the user's approval for a tool call (stdio protocol).
 *
 * Answer with a `permission_response` carrying the same `request_id`.
 */
export interface PermissionRequest {
  type: "permission_request";
  request_id: string;
  tool_use_id: string;
  name: string;
  label: string;
  input: Record<string, unknown>;
  suggested_rule: string;
  reason: string;
  can_remember: boolean;
  change: FileChange | null;
}

/** The todo list changed (stdio protocol). */
export interface TodoUpdate {
  type: "todo_update";
  todos: Record<string, unknown>[];
}

export interface ModeChanged {
  type: "mode_changed";
  mode: string;
}

export interface ModelChanged {
  type: "model_changed";
  model: string;
  context_window: number | null;
}

/** Run an IDE tool in the client; answer with `ide_tool_result`. */
export interface IdeToolRequest {
  type: "ide_tool_request";
  request_id: string;
  name: string;
  input: Record<string, unknown>;
}

export interface SessionList {
  type: "session_list";
  sessions: SessionSummary[];
}

/** The slash commands a `user_message` can start with (for completion). */
export interface CommandList {
  type: "command_list";
  commands: CommandInfo[];
}

/** Earlier user messages to rewind to (answer with a `rewind` message). */
export interface RewindPoints {
  type: "rewind_points";
  points: RewindPoint[];
}

/**
 * The result of a `rewind`. When the conversation was rewound, a
 * `history` event follows with the conversation as it is now.
 */
export interface Rewound {
  type: "rewound";
  code: boolean;
  conversation: boolean;
  actions: RewindAction[];
  prompt: string | null;
}

/** A resumed conversation so far, so the client can show it. */
export interface History {
  type: "history";
  messages: HistoryItem[];
}

/** Code from the project's index added to the user's message (automatic context). */
export interface CodeContext {
  type: "code_context";
  items: CodeContextItem[];
  tokens: number;
}

/**
 * The main model can't see images: the vision model (settings `visionModel`)
 * described the user's images, and the descriptions went to it instead.
 */
export interface ImagesDescribed {
  type: "images_described";
  model: string;
  count: number;
}

/** Code search's state for this project (VS Code's status bar). */
export interface IndexStatus {
  type: "index_status";
  set_up: boolean;
  active: boolean;
  model: string | null;
  store: string | null;
  files: number;
  chunks: number;
  updated: number | null;
  read_only: boolean;
  updating: boolean;
  error: string | null;
  lines: string[];
}

export interface IndexProgress {
  type: "index_progress";
  done: number;
  total: number;
  chunks: number;
}

export interface RagCandidatesList {
  type: "rag_candidates";
  likely: string[];
  other: string[];
  errors: Record<string, unknown>;
}

/**
 * A subagent (Task call) changed: sent when it is queued, starts, calls a
 * tool, waits for a permission, and ends. The front ends draw the agent map
 * from these; `stop_subagent` stops one.
 */
export interface SubagentStatus {
  type: "subagent_status";
  id: string;
  number: number;
  description: string;
  agent_type: string;
  model: string;
  state: "queued" | "running" | "waiting" | "stopping" | "done" | "limit" | "stopped" | "failed";
  steps: number;
  max_steps: number;
  tool_uses: number;
  tokens: number;
  elapsed_ms: number;
  activity: string;
}

/**
 * Critique (`/critic on`): the critic's verdict on the turn's answer.
 * Not final: the agent is fixing the problems and will be reviewed again.
 * Final: the answer has just been shown (passed, out of rounds, or not
 * reviewed: verdict "none").
 */
export interface ReviewResult {
  type: "review_result";
  round: number;
  max_rounds: number;
  verdict: "pass" | "fail" | "none";
  final: boolean;
  summary: string;
  issues: ReviewIssue[];
}

/**
 * Critique was switched on or off: by `set_critique`, `/critic`, or the
 * saved setting (`critic.enabled` in the user's settings) changed in
 * another window or the terminal.
 */
export interface CritiqueChanged {
  type: "critique_changed";
  enabled: boolean;
  source: "you" | "saved";
}

export interface RagSetupResult {
  type: "rag_setup_result";
  ok: boolean;
  message: string;
  settings_file: string | null;
}

export interface Result {
  type: "result";
  subtype: "success" | "error" | "max_turns" | "interrupted";
  is_error: boolean;
  result: string;
  num_turns: number;
  duration_ms: number;
  usage: Record<string, unknown>;
  session_id: string;
  review: Record<string, unknown> | null;
}

export type AgentEvent =
  | SystemInit
  | AssistantDelta
  | ReasoningDelta
  | AssistantMessage
  | ToolUse
  | ToolResult
  | PermissionDenied
  | UsageUpdate
  | Warning
  | Error
  | Compacted
  | PermissionRequest
  | TodoUpdate
  | ModeChanged
  | ModelChanged
  | IdeToolRequest
  | SessionList
  | CommandList
  | RewindPoints
  | Rewound
  | History
  | CodeContext
  | ImagesDescribed
  | IndexStatus
  | IndexProgress
  | RagCandidatesList
  | SubagentStatus
  | ReviewResult
  | CritiqueChanged
  | RagSetupResult
  | Result;

// ---- Client -> agent (stdin) ----

/** What the user has open in the editor, sent with a message. */
export interface IdeContext {
  active_file?: string | null;
  selection?: IdeSelection | null;
  diagnostics?: IdeDiagnostic[];
}

export interface IdeDiagnostic {
  path: string;
  line: number;
  severity: "error" | "warning" | "info" | "hint";
  message: string;
  source?: string | null;
}

export interface IdeSelection {
  path: string;
  start_line: number;
  end_line: number;
  text: string;
}

/**
 * An image the user pasted, dropped or picked. cmcoder checks the bytes
 * (PNG, JPEG, GIF or WebP only) and makes a large one smaller.
 */
export interface ImageAttachment {
  data: string;
  media_type?: string | null;
  name?: string | null;
}

/** Start a turn. Only one turn runs at a time. */
export interface UserMessage {
  type: "user_message";
  text?: string;
  context?: IdeContext | null;
  images?: ImageAttachment[];
}

/** Stop the running turn (like Ctrl+C in the CLI). */
export interface Interrupt {
  type: "interrupt";
}

/** The answer to a `permission_request`. */
export interface PermissionResponse {
  type: "permission_response";
  request_id: string;
  allow: boolean;
  remember?: boolean;
  feedback?: string | null;
}

export interface SetMode {
  type: "set_mode";
  mode: string;
}

export interface SetModel {
  type: "set_model";
  model: string;
}

/**
 * The client can run these IDE tools (e.g. getDiagnostics, openFile).
 *
 * Send once after `system_init`; the agent offers them to the model and
 * asks the client to run them with `ide_tool_request`.
 */
export interface IdeCapabilities {
  type: "ide_capabilities";
  tools: string[];
}

/** The answer to an `ide_tool_request`. */
export interface IdeToolResult {
  type: "ide_tool_result";
  request_id: string;
  content: string;
  is_error?: boolean;
}

/** Ask for this project's saved conversations (answered with `session_list`). */
export interface ListSessions {
  type: "list_sessions";
}

/**
 * Ask for the slash commands (answered with `command_list`). A
 * `user_message` whose text starts with one of them runs it.
 */
export interface ListCommands {
  type: "list_commands";
}

/**
 * Go back to before user message `turn` (from `rewind_points`): undo the
 * agent's file changes (`code`), the conversation, or both. Files outside the
 * project are only restored with `outside`.
 */
export interface Rewind {
  type: "rewind";
  turn: number;
  code?: boolean;
  conversation?: boolean;
  outside?: boolean;
}

/**
 * Code search: the index's state, or update / rebuild / clear it. Answered
 * with `index_status` (and `index_progress` while it works).
 */
export interface Index {
  type: "index";
  action?: "status" | "update" | "rebuild" | "clear";
}

/** The gateways' models, for picking an embedding model (`rag_candidates`). */
export interface RagCandidates {
  type: "rag_candidates";
}

/** Set up code search, as `cmcoder rag setup` does (`rag_setup_result`). */
export interface RagSetup {
  type: "rag_setup";
  embedding_model: string;
  store?: "local" | "chroma-server";
  url?: string | null;
  api_key?: string | null;
  scope?: "user" | "project";
  read_only?: boolean;
  index_now?: boolean;
}

/**
 * Stop one subagent (a `subagent_status` id); the turn and the other
 * subagents go on. It writes a report of what it found so far.
 */
export interface StopSubagent {
  type: "stop_subagent";
  id: string;
}

/**
 * Switch critique on or off (the panel's checkbox). `save`: also save it
 * as `critic.enabled` in the user's settings, which every running cmcoder
 * follows (the terminal, the TUI, other VS Code windows).
 */
export interface SetCritique {
  type: "set_critique";
  enabled: boolean;
  save?: boolean;
}

/** Stop the running turn, save the session and exit (EOF does the same). */
export interface Shutdown {
  type: "shutdown";
}

export type ClientMessage =
  | UserMessage
  | Interrupt
  | PermissionResponse
  | SetMode
  | SetModel
  | IdeCapabilities
  | IdeToolResult
  | ListSessions
  | ListCommands
  | Rewind
  | Index
  | RagCandidates
  | RagSetup
  | StopSubagent
  | SetCritique
  | Shutdown;
